[package]
name = "stats_runer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9"
glib-sys = "0.10"
gio = "0.9"
twitchchat = { version = "0.12.0-alpha.2" }
